version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: callcenter
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
